version: '3'
services:
  hello:
    build: .
    ports:
      - "4000:80"
    networks:
      - "workshop"
  hello_db:
    image: "postgres"
    networks:
      - "workshop"

networks:
  workshop:

volumes:
  workshop_data:
